ALTER TABLE INODE ALTER COLUMN OWNER VARCHAR(100);

ALTER TABLE CONTENT_RATING ADD USER_IP VARCHAR(255);
ALTER TABLE CONTENT_RATING ADD LONG_LIVE_COOKIE_ID VARCHAR(255);

alter table content_rating add "identifier" numeric(19,0);
UPDATE CONTENT_RATING SET IDENTIFIER = (INODE - 1);
ALTER TABLE CONTENT_RATING DROP COLUMN INODE;

ALTER TABLE WEB_FORM ADD USER_INODE BIGINT DEFAULT 0;
ALTER TABLE WEB_FORM ADD CATEGORIES VARCHAR(255);

EXEC SP_RENAME 'CONTENTLET.NUMBER1','FLOAT1','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER2','FLOAT2','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER3','FLOAT3','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER4','FLOAT4','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER5','FLOAT5','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER6','FLOAT6','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER7','FLOAT7','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER8','FLOAT8','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER9','FLOAT9','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER10','FLOAT10','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER11','FLOAT11','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER12','FLOAT12','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER13','FLOAT13','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER14','FLOAT14','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER15','FLOAT15','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER16','FLOAT16','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER17','FLOAT17','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER18','FLOAT18','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER19','FLOAT19','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER20','FLOAT20','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER21','FLOAT21','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER22','FLOAT22','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER23','FLOAT23','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER24','FLOAT24','COLUMN';
EXEC SP_RENAME 'CONTENTLET.NUMBER25','FLOAT25','COLUMN';