CREATE TABLE CHALLENGE_QUESTION (
	CQUESTIONID CHARACTER VARYING(100) PRIMARY KEY,
	CQTEXT TEXT
);

ALTER TABLE USER_PROXY
	ADD COLUMN CQUESTIONID CHARACTER VARYING(100);

ALTER TABLE USER_PROXY
	ADD CONSTRAINT FK_USER_PROXY_CQUESTIONID FOREIGN KEY(CQUESTIONID) REFERENCES CHALLENGE_QUESTION(CQUESTIONID);

ALTER TABLE USER_PROXY
	ADD COLUMN CQANSWER TEXT;